layout_spectrum: 0.188172
color:
  saturation: 0.297491
  brandStrength: 1
  lightness: 0.7616488
  brandColors:
    - '#737174'
    - '#3A3637'
    - '#EBEBED'
    - '#C7C6C2'
    - '#9B9A95'
  rhythmicContrast: 0.327957
typography_spectrum: 0.4336918
name: Whaddupanda
